In [1]:
pip install requests

Requirement already satisfied: requests in d:\anaconda\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests as rq

record = []

for i in range(1,6):
    url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page={i}&sparkline=False"
    response = rq.get(url)

    if response.status_code == 200:
        data = response.json()
        record.extend(data)

In [3]:
# Get the stock prices of all bit coins
import pandas as pd

In [4]:
df_stock = pd.DataFrame(record)
df_stock.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,7079423.00,141666553245070,1,1.416666e+14,4.291890e+12,7121275.00,...,2.001874e+07,2.100000e+07,11187013.00,-36.71748,2025-10-06T18:57:42.558Z,3993.420000,1.771772e+05,2013-07-05T00:00:00.000Z,None,2026-04-21T06:17:58.761Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,215835.00,26052794281446,2,2.605279e+13,1.942266e+12,217901.00,...,1.206900e+08,NaN,431946.00,-50.03180,2025-08-24T19:21:03.333Z,28.130000,7.671448e+05,2015-10-20T00:00:00.000Z,"{'times': 39.75910903904445, 'currency': 'btc'...",2026-04-21T06:17:58.651Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,93.41,17551020464710,3,1.806162e+13,6.597125e+12,93.41,...,1.933829e+11,NaN,105.52,-11.49769,2025-01-25T16:51:57.989Z,36.860000,1.533574e+02,2015-03-02T00:00:00.000Z,None,2026-04-21T06:17:57.732Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,133.47,8223821942121,4,1.335502e+13,2.440256e+11,133.70,...,9.998568e+10,1.000000e+11,313.99,-57.49221,2025-07-21T15:02:00.541Z,0.159343,8.366209e+04,2013-08-16T00:00:00.000Z,None,2026-04-21T06:17:57.932Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,58904.00,7938720442517,5,7.938720e+12,9.223610e+10,59018.00,...,1.347866e+08,2.000000e+08,121422.00,-51.48799,2025-10-13T08:41:24.131Z,2.580000,2.278826e+06,2017-10-19T00:00:00.000Z,None,2026-04-21T06:17:58.230Z

In [5]:
df_stock_filter = df_stock[['id', 'symbol', 'name', 'current_price', 'market_cap', 'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply', 'ath', 'atl', 'last_updated']]

df_stock_filter['last_updated'] = pd.to_datetime(df_stock_filter['last_updated']).dt.date

df_stock_filter.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3436067488.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock_filter['last_updated'] = pd.to_datetime(df_stock_filter['last_updated']).dt.date

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7079423.00,141666553245070,1,4.291890e+12,2.001874e+07,2.001874e+07,11187013.00,3993.420000,2026-04-21
1,ethereum,eth,Ethereum,215835.00,26052794281446,2,1.942266e+12,1.206900e+08,1.206900e+08,431946.00,28.130000,2026-04-21
2,tether,usdt,Tether,93.41,17551020464710,3,6.597125e+12,1.879160e+11,1.933829e+11,105.52,36.860000,2026-04-21
3,ripple,xrp,XRP,133.47,8223821942121,4,2.440256e+11,6.156968e+10,9.998568e+10,313.99,0.159343,2026-04-21
4,binancecoin,bnb,BNB,58904.00,7938720442517,5,9.223610e+10,1.347866e+08,1.347866e+08,121422.00,2.580000,2026-04-21

In [6]:
# TOP 3 coins - historical prices

In [7]:
url = f"https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=inr&days=365"
response = rq.get(url)
data = response.json()

In [29]:
coin_id = ["bitcoin","ethereum","tether"]
rows = []
pd.options.display.float_format = '{:.2f}'.format

for i in coin_id:
    url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
    response = rq.get(url)

    if response.status_code == 200:
        data = response.json()
    
        for timestamp, price in data['prices']:
            rows.append({
                'coin_id': i,
                'timestamp': timestamp,
                'price_inr': price
            })
        else:
            print('Limit Exceeded')

top_3_coins = pd.DataFrame(rows)
top_3_coins['timestamp'] = pd.to_datetime(top_3_coins['timestamp'], unit='ms').dt.date
top_3_coins

Limit Exceeded
Limit Exceeded

      coin_id   timestamp  price_inr
0     bitcoin  2025-04-22 7447341.99
1     bitcoin  2025-04-23 7975735.89
2     bitcoin  2025-04-24 8003280.21
3     bitcoin  2025-04-25 8000169.78
4     bitcoin  2025-04-26 8092178.48
..        ...         ...        ...
727  ethereum  2026-04-18  224191.18
728  ethereum  2026-04-19  217702.44
729  ethereum  2026-04-20  209729.87
730  ethereum  2026-04-21  215583.94
731  ethereum  2026-04-21  215640.91

[732 rows x 3 columns]

In [9]:
#OIL PRICES

In [10]:
oil_price_all = pd.read_csv('https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv')
oil_price_filtered = oil_price_all[(oil_price_all['Date'] >= '2020-01-01') & (oil_price_all['Date'] <= '2026-01-31')]
oil_price_filtered.tail()

             Date  Price
10084  2026-01-26  60.46
10085  2026-01-27  62.04
10086  2026-01-28  62.75
10087  2026-01-29  64.77
10088  2026-01-30  64.50

In [11]:
pip install yfinance

Requirement already satisfied: yfinance in d:\anaconda\lib\site-packages (1.2.2)
Requirement already satisfied: pandas>=1.3.0 in d:\anaconda\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in d:\anaconda\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in d:\anaconda\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in d:\anaconda\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in d:\anaconda\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in d:\anaconda\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in d:\anaconda\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in d:\anaconda\lib\site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in d:\anaconda\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in d:\anaconda\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in d:\anaconda\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in d:\anaconda\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>1.2 in d:\anaconda\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\anaconda\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in d:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in d:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.1.4)
Requirement already satisfied: rich in d:\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in d:\anaconda\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in d:\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import yfinance as yf

ticker = ["^GSPC", "^IXIC", "^NSEI"]
start_date = '2020-01-01'
end_date = '2026-01-30'

df_yahoo = yf.download(ticker, start=start_date, end = end_date, group_by = 'ticker')
df_yahoo.head()

[*********************100%***********************]  3 of 3 completed

Ticker        ^NSEI                                        ^GSPC          \
Price          Open     High      Low    Close    Volume    Open    High
Date
2020-01-01 12202.15 12222.20 12165.30 12182.50 304100.00     NaN     NaN
2020-01-02 12198.55 12289.90 12195.25 12282.20 407700.00 3244.67 3258.14
2020-01-03 12261.10 12265.60 12191.35 12226.65 428800.00 3226.36 3246.15
2020-01-06 12170.60 12179.10 11974.20 11993.05 396500.00 3217.55 3246.84
2020-01-07 12079.10 12152.15 12005.35 12052.95 447800.00 3241.86 3244.91

Ticker                                     ^IXIC                          \
Price          Low   Close        Volume    Open    High     Low   Close
Date
2020-01-01     NaN     NaN           NaN     NaN     NaN     NaN     NaN
2020-01-02 3235.53 3257.85 3459930000.00 9039.46 9093.43 9010.89 9092.19
2020-01-03 3222.34 3234.85 3484700000.00 8976.43 9065.76 8976.43 9020.77
2020-01-06 3214.64 3246.28 3702460000.00 8943.50 9072.41 8943.50 9071.47
2020-01-07 3232.43 3237.18 3435910000.00 9076.64 9091.93 9042.55 9068.58

Ticker
Price             Volume
Date
2020-01-01           NaN
2020-01-02 2862700000.00
2020-01-03 2586520000.00
2020-01-06 2810450000.00
2020-01-07 2381740000.00

In [13]:
df_yahoo.dropna()

Ticker        ^NSEI                                        ^GSPC          \
Price          Open     High      Low    Close    Volume    Open    High
Date
2020-01-02 12198.55 12289.90 12195.25 12282.20 407700.00 3244.67 3258.14
2020-01-03 12261.10 12265.60 12191.35 12226.65 428800.00 3226.36 3246.15
2020-01-06 12170.60 12179.10 11974.20 11993.05 396500.00 3217.55 3246.84
2020-01-07 12079.10 12152.15 12005.35 12052.95 447800.00 3241.86 3244.91
2020-01-08 11939.10 12044.95 11929.60 12025.35 446000.00 3238.59 3267.07
...             ...      ...      ...      ...       ...     ...     ...
2026-01-22 25344.15 25435.75 25168.50 25289.90 486400.00 6914.44 6934.75
2026-01-23 25344.60 25347.95 25025.30 25048.65 393900.00 6907.85 6932.96
2026-01-27 25063.35 25246.65 24932.55 25175.40 618700.00 6965.96 6988.82
2026-01-28 25258.85 25372.10 25187.65 25342.75 574900.00 7002.00 7002.28
2026-01-29 25345.00 25458.15 25159.80 25418.90 582400.00 6977.74 6992.84

Ticker                                      ^IXIC                             \
Price          Low   Close        Volume     Open     High      Low    Close
Date
2020-01-02 3235.53 3257.85 3459930000.00  9039.46  9093.43  9010.89  9092.19
2020-01-03 3222.34 3234.85 3484700000.00  8976.43  9065.76  8976.43  9020.77
2020-01-06 3214.64 3246.28 3702460000.00  8943.50  9072.41  8943.50  9071.47
2020-01-07 3232.43 3237.18 3435910000.00  9076.64  9091.93  9042.55  9068.58
2020-01-08 3236.67 3253.05 3726840000.00  9068.03  9168.89  9059.38  9129.24
...            ...     ...           ...      ...      ...      ...      ...
2026-01-22 6893.62 6913.35 5307580000.00 23440.71 23503.16 23335.15 23436.02
2026-01-23 6895.50 6915.61 4871930000.00 23440.92 23610.74 23374.26 23501.24
2026-01-27 6958.83 6978.60 5331720000.00 23734.75 23865.26 23694.38 23817.10
2026-01-28 6963.46 6978.03 5507670000.00 23965.11 23988.27 23775.49 23857.45
2026-01-29 6870.80 6969.01 6877780000.00 23830.92 23840.55 23232.78 23685.12

Ticker
Price             Volume
Date
2020-01-02 2862700000.00
2020-01-03 2586520000.00
2020-01-06 2810450000.00
2020-01-07 2381740000.00
2020-01-08 2472620000.00
...                  ...
2026-01-22 9034850000.00
2026-01-23 8228760000.00
2026-01-27 8026050000.00
2026-01-28 8151580000.00
2026-01-29 8782210000.00

[1455 rows x 15 columns]

In [14]:
df_yahoo.isnull().sum()

Ticker  Price
^NSEI   Open      72
        High      72
        Low       72
        Close     72
        Volume    72
^GSPC   Open      50
        High      50
        Low       50
        Close     50
        Volume    50
^IXIC   Open      50
        High      50
        Low       50
        Close     50
        Volume    50
dtype: int64

In [15]:
df_yahoo_gspc = df_yahoo["^GSPC"].reset_index()
df_yahoo_ixic = df_yahoo["^IXIC"].reset_index()
df_yahoo_nsei = df_yahoo["^NSEI"].reset_index()

df_yahoo_nsei['ticker'] = '^NSEI'
df_yahoo_gspc['ticker'] = '^GSPC'
df_yahoo_ixic['ticker'] = '^IXIC'

df_yahoo_comibned = [df_yahoo_gspc,df_yahoo_ixic,df_yahoo_nsei]
df_yahoo_tickers = pd.concat(df_yahoo_comibned)

df_yahoo_tickers.sample(4)

Price       Date     Open     High      Low    Close        Volume ticker
1196  2024-08-13 24342.35 24359.95 24116.50 24139.00     239700.00  ^NSEI
1276  2024-12-03 24367.50 24481.35 24280.00 24457.15     339500.00  ^NSEI
1228  2024-09-26  5762.22  5767.37  5721.01  5745.37 4391180000.00  ^GSPC
1070  2024-02-16 22020.30 22068.65 21968.95 22040.70     343900.00  ^NSEI

In [16]:
df_yahoo_tickers.sample()
oil_price_filtered.sample()
top_3_coins.sample()
df_stock_filter.sample()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
669,the-innovation-game,tig,The Innovation Game,101.28,2807968019,670,786800236.00,27730369.78,48168188.23,364.24,9.92,2026-04-21

In [17]:
# Establish Python connection to MYSQL
# create 4 tables
# insert 4 dataframes to sql table
#

In [18]:
pip install pymysql

Requirement already satisfied: pymysql in d:\anaconda\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import pymysql

conn = pymysql.connect(
    host = "localhost",
    user = "root",
    password = "sql1234",
    database = 'cross_market_analysis'
)
cursor = conn.cursor()

In [22]:
cursor.execute('''create table Cryptocurrencies
(
id VARCHAR(100) PRIMARY KEY,
symbol VARCHAR(10),
name VARCHAR(100),
current_price DECIMAL(20,6),
market_cap BIGINT,
market_cap_rank INT,
total_volume BIGINT,
circulating_supply DECIMAL(20,6),	
total_supply DECIMAL(20,6),
ath DECIMAL(20,6),
atl DECIMAL(20,6),
date DATE
);''')

0

In [23]:
cursor.execute('''create table Crypto_prices
                (
                COIN_ID VARCHAR(100),
                DATE DATE,
                PRICE_INR DECIMAL(20,6),
                FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies(id)
                );''')

0

In [24]:
cursor.execute('''create table Oil_prices
(
DATE DATE primary key,
PRICE_INR DECIMAL(20,6)
);''')

0

In [25]:
cursor.execute('''create table stock_prices
(
DATE DATE primary key,
open DECIMAL(20,6),
high DECIMAL(20, 6),
low DECIMAL(20, 6),
close DECIMAL(20, 6),
volume bigint,
ticker varchar(50)
);''')

0

In [26]:
cursor.execute('select * from stock_prices')

0

In [30]:
oil_price_filtered = oil_price_filtered.rename(columns={
    'Price_INT': 'Price_INR'
})
oil_price_filtered.sample()

            Date  Price
9768  2024-10-15  71.22

In [37]:
# Now try to write the dataframe to SQL with the correct engine
from sqlalchemy import create_engine

conn.close()
conn = pymysql.connect(
    host = "localhost",
    user = "root",
    password = "sql1234",
    database = 'test'
)
cursor = conn.cursor()

# Create SQLAlchemy engine using the PyMySQL connection
engine = create_engine('mysql+pymysql://root:sql1234@localhost/test')


oil_price_filtered.to_sql("oil_prices",if_exists="replace",con =engine)

1520

In [38]:
cursor.execute('select * from oil_prices limit 7')
results = cursor.fetchall()

for i in results:
    print(i)

(8569, '2020-01-02', 61.17)
(8570, '2020-01-03', 63.0)
(8571, '2020-01-06', 63.27)
(8572, '2020-01-07', 62.7)
(8573, '2020-01-08', 59.65)
(8574, '2020-01-09', 59.56)
(8575, '2020-01-10', 59.02)

In [78]:
top_3_coins.sample(5)

      coin_id   timestamp   price_inr
531  ethereum  2025-10-04   400707.46
49    bitcoin  2025-06-10  9455619.18
74    bitcoin  2025-07-05  9250500.06
402  ethereum  2025-05-28   227238.58
166   bitcoin  2025-10-05 10859533.64

In [40]:
df_yahoo_tickers.to_sql("stock_prices",if_exists="replace",con =engine)

4731

In [41]:
chunk_size = 100  # Adjust based on your database limits

df_stock_filter = df_stock_filter.rename(columns = {'last_updated':'date'})

if 'date' in df_stock_filter.columns:
    df_stock_filter['date'] = pd.to_datetime(df_stock_filter['date'])

try:
    for i in range(0, len(df_stock_filter), chunk_size):
        df_chunk = df_stock_filter.iloc[i:i+chunk_size]
        df_chunk.to_sql("cryptocurrencies", if_exists="replace", con=engine, index=False)
        print(f"Inserted chunk {i//chunk_size + 1} of {(len(df_stock_filter) + chunk_size - 1)//chunk_size}")
except Exception as e:
    print(f"Error inserting data: {e}")

Inserted chunk 1 of 13
Inserted chunk 2 of 13
Inserted chunk 3 of 13
Inserted chunk 4 of 13
Inserted chunk 5 of 13
Inserted chunk 6 of 13
Inserted chunk 7 of 13
Inserted chunk 8 of 13
Inserted chunk 9 of 13
Inserted chunk 10 of 13
Inserted chunk 11 of 13
Inserted chunk 12 of 13
Inserted chunk 13 of 13

In [42]:
top_3_coins.to_sql("crypto_prices",if_exists="replace",con =engine)

732

In [43]:
conn.close()
conn = pymysql.connect(
    host = "localhost",
    user = "root",
    password = "sql1234",
    database = 'test'
)
cursor = conn.cursor()

cursor.execute('select * from crypto_prices limit 5')
results = cursor.fetchall()

for i in results:
    print(i)

(0, 'bitcoin', datetime.date(2025, 4, 22), 7447341.987486609)
(1, 'bitcoin', datetime.date(2025, 4, 23), 7975735.892697773)
(2, 'bitcoin', datetime.date(2025, 4, 24), 8003280.21321444)
(3, 'bitcoin', datetime.date(2025, 4, 25), 8000169.783417303)
(4, 'bitcoin', datetime.date(2025, 4, 26), 8092178.475391482)

In [44]:
# Cryptocurrencies Queries

In [45]:
# 1. Find the top 3 cryptocurrencies by market cap.

query = 'SELECT * FROM cryptocurrencies ORDER BY market_cap DESC LIMIT 3'
df_top3 = pd.read_sql(query, conn)
print(df_top3)

                       id symbol                    name  current_price  \
0  bertram-the-pomeranian   bert  Bertram The Pomeranian           0.96
1             anzens-usda   usda             Anzens USDA          93.16
2            rupiah-token   idrt            Rupiah Token           0.01

   market_cap  market_cap_rank  total_volume  circulating_supply  \
0   945038374             1201  129867993.00        976883064.94
1   938861380             1203   35805349.00         10081677.00
2   937204128             1205        418.67     173856905811.00

     total_supply    ath   atl       date
0    976883064.94  15.92  0.13 2026-04-21
1     10081677.00 429.97 47.02 2026-04-21
2 173856905811.00   0.02  0.00 2026-04-21

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\585475281.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_top3 = pd.read_sql(query, conn)

In [46]:
# 2. List all coins where circulating supply exceeds 90% of total supply.

query = 'SELECT id FROM cryptocurrencies WHERE circulating_supply > (total_supply * 0.90)'
df_topcoins = pd.read_sql(query, conn)
print(df_topcoins)

                                                   id
0                              bertram-the-pomeranian
1                                         anzens-usda
2                                        rupiah-token
3                                              eusd-2
4                                          defi-money
5                                    milady-meme-coin
6                                          real-token
7                                            alpha-fi
8                                            ellipsis
9                                           stake-dao
10                                       switch-token
11                                           crob-mob
12                                              melon
13                                     freedom-dollar
14                                      landwolf-0x67
15                                    oraichain-token
16                                               foom
17                                            crepe-2
18                                         epic-chain
19                                     i-love-puppies
20                                      debtreliefbot
21                                          eitherway
22                                          lobster-2
23                                     kekius-maximus
24  ishares-core-msci-emerging-markets-etf-ondo-to...
25                                       infiniticoin
26                                            syscoin
27                                   freedom-of-money

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\1175572712.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_topcoins = pd.read_sql(query, conn)

In [47]:
# 3. Get coins that are within 10% of their all-time-high (ATH)

query = 'select * from cryptocurrencies where ath <= (select max(ath)*0.10 from cryptocurrencies)'
df_max_ath = pd.read_sql(query, conn)
print(df_max_ath)

                        id            symbol                    name  \
0   bertram-the-pomeranian              bert  Bertram The Pomeranian
1                  ostrich              rich                 Ostrich
2              anzens-usda              usda             Anzens USDA
3             rupiah-token              idrt            Rupiah Token
4                      qie               qie          QIE Blockchain
5                   eusd-2              eusd                    eUSD
6               defi-money             money              Defi.money
7         milady-meme-coin             ladys        Milady Meme Coin
8               real-token              real                  RealFi
9           hamster-kombat             hmstr          Hamster Kombat
10                alpha-fi             alpha                Alpha Fi
11                ellipsis               eps          Ellipsis [OLD]
12               stake-dao               sdt               Stake DAO
13            switch-token            switch            Switch Token
14        particle-network             parti        Particle Network
15                crob-mob              crob                Crob Mob
16           tars-protocol               tai                 TARS AI
17               autonolas              olas               Autonolas
18               jumptoken              jmpt               JumpToken
19                    arpa              arpa                    ARPA
20          freedom-dollar              fusd          Freedom Dollar
21       polyhedra-network               zkj       Polyhedra Network
22           landwolf-0x67              wolf                LandWolf
23         wyde-end-hunger               eat        WYDE: End Hunger
24                    foom              foom                    Foom
25                 crepe-2             crepe                   CREPE
26            hana-network              hana            Hana Network
27              epic-chain              epic              Epic Chain
28          i-love-puppies           puppies          I love puppies
29           debtreliefbot               drb           DebtReliefBot
30               eitherway            either               Eitherway
31                ethichub             ethix                   Ethix
32        milady-cult-coin              cult        Milady Cult Coin
33               lobster-2                龙虾            龙虾 (Lobster)
34                 myshell             shell                 MyShell
35         conscious-token         conscious         Conscious Token
36          kekius-maximus            kekius          Kekius Maximus
37            infiniticoin              inco            InfinitiCoin
38                 syscoin               sys                 Syscoin
39          bitlayer-bitvm               btr                Bitlayer
40            world-assets               inc             WorldAssets
41        freedom-of-money  freedom of money        Freedom of Money

    current_price  market_cap  market_cap_rank  total_volume  \
0            0.96   945038374             1201  129867993.00
1           16.30   902066476             1202          0.00
2           93.16   938861380             1203   35805349.00
3            0.01   937204128             1205        418.67
4           11.06   935236973             1206     313006.00
5           93.36   933514148             1207    1215679.00
6           93.32   932513307             1208      15229.07
7            0.00   932243565             1204   49767521.00
8            0.93   931683406             1209    8756883.00
9            0.01   931077659             1210  256477244.00
10          93.88   930738221             1212     407620.00
11           1.33   930003984             1215       3787.28
12          13.74   929878966             1214     167273.00
13           0.02   929694574             1211      56990.00
14           3.99   928286431             1216 2000562712.00
15           0.92   917741990             1217       1471.10
16           1.57   919305347             1218   49097372.00
17           3.87   916517188             1219   17500516.00
18          62.06   916016933             1220    1145262.00
19           0.92   908461671             1223  371879296.00
20          93.41   905977210             1225   16103279.00
21           1.80   905098299             1224  143541060.00
22           0.00   904486653             1226   69356311.00
23           0.09   902407323             1227    5646735.00
24           0.00   899492792             1230    3696277.00
25           0.00   898841051             1236   37116282.00
26           3.73   895828006             1232  140845369.00
27          26.69   893742352             1234  450924340.00
28           0.00   892316892             1233 1182457635.00
29           0.01   889316607             1237  191751537.00
30           8.85   886423220             1238  300560168.00
31          12.55   884552367             1239     461829.00
32           0.02   882117412             1240   67562743.00
33           0.88   881608509             1241  150274400.00
34           3.26   879068903             1242 1059378286.00
35           1.87   876298219             1243    4483978.00
36           0.88   877601298             1244   94874752.00
37           0.87   872084926             1246       1200.84
38           0.98   869352737             1247  172700865.00
39           3.33   867980966             1248  720823526.00
40           9.62   867595823             1249   10921300.00
41           0.87   867689050             1250  264122401.00

    circulating_supply       total_supply     ath   atl       date
0         976883064.94       976883064.94   15.92  0.13 2026-04-21
1          55350032.22       100000000.00  289.41  9.58 2026-03-04
2          10081677.00        10081677.00  429.97 47.02 2026-04-21
3      173856905811.00    173856905811.00    0.02  0.00 2026-04-21
4          84544400.70       150000565.00   19.27  0.01 2026-04-21
5          10000000.00        10000000.00   95.20 90.12 2026-04-21
6           9994958.76         9994958.76   95.25 80.31 2026-04-21
7   888000888000888.00 888000888000888.00    0.00  0.00 2026-04-21
8        1000000000.00      1000000000.00    3.73  0.52 2026-04-21
9       64375000000.00    100000000000.00    0.60  0.01 2026-04-21
10          9908628.10        10000000.00  466.89 49.02 2026-04-21
11        698445817.39       723701571.80 1553.34  1.24 2026-04-21
12         67665437.83        69417883.02 1266.02  1.25 2026-04-21
13      50000000000.00     50000000000.00    0.70  0.00 2026-04-21
14        233000000.00      1000000000.00   35.76  3.53 2026-04-21
15       1000000000.00      1000000000.00    5.08  0.89 2026-04-20
16        586681333.53       894996126.41   41.87  1.01 2026-04-21
17        236666339.01       473215315.18  705.69  3.21 2026-04-21
18         14759990.00        30789989.90  242.32 50.95 2026-04-21
19        982174603.29      1999999999.99   20.01  0.26 2026-04-21
20          9700000.00         9700000.00   95.26 84.35 2026-04-21
21        504194446.00      1000000000.00  332.97  1.72 2026-04-21
22     902159505150.00    902159505150.00    0.02  0.00 2026-04-21
23      10000000000.00    100000000000.00    0.10  0.00 2026-04-21
24  175000000000000.00 175000000000000.00    0.00  0.00 2026-04-21
25     690000000000.00    690000000000.00    0.01  0.00 2026-04-21
26        240000000.00      1000000000.00   21.77  0.79 2026-04-21
27         33600000.00        33600000.00  278.29 21.96 2026-04-21
28   42069000000000.00  42069000000000.00    0.00  0.00 2026-04-21
29     100000000000.00    100000000000.00    0.04  0.00 2026-04-21
30         99999934.85        99999934.85   16.68  6.64 2026-04-21
31         70498105.00       100000000.00   75.29  4.68 2026-04-21
32      46877276898.21    100000000000.00    0.65  0.01 2026-04-21
33       1000000000.00      1000000000.00    2.47  0.13 2026-04-21
34        270000000.00      1000000000.00   59.66  2.43 2026-04-21
35        468351273.91      1000000000.00   37.41  1.84 2026-04-21
36       1000000000.00      1000000000.00   34.33  0.06 2026-04-21
37       1000000000.00      1000000000.00    1.80  0.53 2026-04-20
38        882992490.91       882992490.91   97.03  0.01 2026-04-21
39        261600000.00      1000000000.00   21.48  2.13 2026-04-21
40         90000000.00       300000000.00  102.33  7.76 2026-04-21
41       1000000000.00      1000000000.00    2.01  0.27 2026-04-21

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\2097303950.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_max_ath = pd.read_sql(query, conn)

In [48]:
# 4. Find the average market cap rank of coins with volume above $1B.

query = 'SELECT AVG(market_cap_rank) AS average_rank FROM cryptocurrencies WHERE total_volume > 1000000000'
df_avg_market_cap = pd.read_sql(query, conn)
print(df_avg_market_cap)

   average_rank
0       1230.33

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3534802091.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_avg_market_cap = pd.read_sql(query, conn)

In [49]:
# 5. Get the most recently updated coin.

query = 'SELECT id, date FROM cryptocurrencies order by date desc limit 1'
df_recent_update_coin = pd.read_sql(query, conn)
print(df_recent_update_coin)

                       id       date
0  bertram-the-pomeranian 2026-04-21

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3846583313.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_recent_update_coin = pd.read_sql(query, conn)

In [50]:
# Crypto_prices Queries

In [51]:
# 1. Find the highest daily price of Bitcoin in the last 365 days.

query = "select timestamp, max(price_inr) max_price from crypto_prices where coin_id = 'bitcoin' group by timestamp order by timestamp desc"
df_recent_update_coin = pd.read_sql(query, conn)
print(df_recent_update_coin)

      timestamp  max_price
0    2026-04-21 7072332.37
1    2026-04-20 6839333.55
2    2026-04-19 7012640.79
3    2026-04-18 7142282.97
4    2026-04-17 6992493.01
..          ...        ...
360  2025-04-26 8092178.48
361  2025-04-25 8000169.78
362  2025-04-24 8003280.21
363  2025-04-23 7975735.89
364  2025-04-22 7447341.99

[365 rows x 2 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\473420075.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_recent_update_coin = pd.read_sql(query, conn)

In [52]:
#2.Calculate the average daily price of Ethereum in the past 1 year

query = "select timestamp, avg(price_inr) avg_price from crypto_prices where coin_id = 'Ethereum' group by timestamp order by timestamp desc"
df_avg_price_coin = pd.read_sql(query, conn)
print(df_avg_price_coin)

      timestamp  avg_price
0    2026-04-21  215612.43
1    2026-04-20  209729.87
2    2026-04-19  217702.44
3    2026-04-18  224191.18
4    2026-04-17  218542.62
..          ...        ...
360  2025-04-26  152736.09
361  2025-04-25  150793.82
362  2025-04-24  153384.69
363  2025-04-23  149984.44
364  2025-04-22  134334.01

[365 rows x 2 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\1228622849.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_avg_price_coin = pd.read_sql(query, conn)

In [53]:
#3. Show the daily price trend of Bitcoin in January 2026

query = "select * from crypto_prices where coin_id = 'bitcoin' and timestamp between '2026-01-01' and '2026-01-31' order by timestamp"
df_jan_price_coin = pd.read_sql(query, conn)
print(df_jan_price_coin)

    index  coin_id   timestamp  price_inr
0     254  bitcoin  2026-01-01 7875103.91
1     255  bitcoin  2026-01-02 7982611.09
2     256  bitcoin  2026-01-03 8094664.57
3     257  bitcoin  2026-01-04 8154755.98
4     258  bitcoin  2026-01-05 8224912.97
5     259  bitcoin  2026-01-06 8475311.20
6     260  bitcoin  2026-01-07 8443838.29
7     261  bitcoin  2026-01-08 8200790.87
8     262  bitcoin  2026-01-09 8179932.13
9     263  bitcoin  2026-01-10 8169727.59
10    264  bitcoin  2026-01-11 8164051.83
11    265  bitcoin  2026-01-12 8196362.96
12    266  bitcoin  2026-01-13 8214254.51
13    267  bitcoin  2026-01-14 8600260.48
14    268  bitcoin  2026-01-15 8754772.56
15    269  bitcoin  2026-01-16 8637202.77
16    270  bitcoin  2026-01-17 8665871.04
17    271  bitcoin  2026-01-18 8641731.27
18    272  bitcoin  2026-01-19 8504968.62
19    273  bitcoin  2026-01-20 8414003.97
20    274  bitcoin  2026-01-21 8046939.83
21    275  bitcoin  2026-01-22 8179241.97
22    276  bitcoin  2026-01-23 8189307.78
23    277  bitcoin  2026-01-24 8190756.88
24    278  bitcoin  2026-01-25 8167427.83
25    279  bitcoin  2026-01-26 7931480.81
26    280  bitcoin  2026-01-27 8098992.12
27    281  bitcoin  2026-01-28 8165356.49
28    282  bitcoin  2026-01-29 8206661.92
29    283  bitcoin  2026-01-30 7762053.97
30    284  bitcoin  2026-01-31 7714332.82

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\2008880670.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_jan_price_coin = pd.read_sql(query, conn)

In [54]:
#4. Find the coin with the highest average price over 1 year.
query = "select coin_id, avg(price_inr) from crypto_prices group by coin_id order by 2 desc limit 1"
df_high_avg_coin = pd.read_sql(query, conn)
print(df_high_avg_coin)

   coin_id  avg(price_inr)
0  bitcoin      8562544.04

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\2880025840.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_high_avg_coin = pd.read_sql(query, conn)

In [55]:
#5. Get the % change in Bitcoin’s price between May 2025 and Mar 2026

query = '''WITH StartPrice AS (
    SELECT price_inr 
    FROM crypto_prices 
    WHERE coin_id = 'bitcoin' AND timestamp = '2025-05-01'
),
EndPrice AS (
    SELECT price_inr 
    FROM crypto_prices 
    WHERE coin_id = 'bitcoin' AND timestamp = '2026-03-31'
)
SELECT 
    ((e.price_inr - s.price_inr) / s.price_inr) * 100 AS percentage_change
FROM StartPrice s, EndPrice e'''
df_change_per_coin = pd.read_sql(query, conn)
print(df_change_per_coin)

   percentage_change
0             -21.03

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3089648063.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_change_per_coin = pd.read_sql(query, conn)

In [56]:
# OIL_PRICES QUERY

In [57]:
#1. Find the highest oil price in the last 5 years.

    query = '''SELECT MAX(price) AS highest_price
    FROM oil_prices
    WHERE date BETWEEN (SELECT DATE_SUB(MAX(date), INTERVAL 5 YEAR) FROM oil_prices) 
                   AND (SELECT MAX(date) FROM oil_prices)'''
df_high_oil_price = pd.read_sql(query, conn)
print(df_high_oil_price)

   highest_price
0         123.64

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3380044299.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_high_oil_price = pd.read_sql(query, conn)

In [58]:
#2. Get the average oil price per year.

query = '''select year(date), avg(price) avg_oil_price  from oil_prices group by year(date) order by 1 desc'''
df_avg_oil_price = pd.read_sql(query, conn)
print(df_avg_oil_price)

   year(date)  avg_oil_price
0        2026          60.04
1        2025          65.39
2        2024          76.63
3        2023          77.58
4        2022          94.90
5        2021          68.14
6        2020          39.16

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\728008776.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_avg_oil_price = pd.read_sql(query, conn)

In [59]:
#3. Show oil prices during COVID crash (March–April 2020)

query = '''select * from oil_prices where date >= '2020-03-01' and date <= '2020-04-30' order by date'''
df_covid_crash_price = pd.read_sql(query, conn)
print(df_covid_crash_price)

    index        Date  Price
0    8609  2020-03-02  46.78
1    8610  2020-03-03  47.27
2    8611  2020-03-04  46.78
3    8612  2020-03-05  45.90
4    8613  2020-03-06  41.14
5    8614  2020-03-09  31.05
6    8615  2020-03-10  34.47
7    8616  2020-03-11  33.13
8    8617  2020-03-12  31.56
9    8618  2020-03-13  31.72
10   8619  2020-03-16  28.96
11   8620  2020-03-17  26.96
12   8621  2020-03-18  20.48
13   8622  2020-03-19  25.09
14   8623  2020-03-20  19.48
15   8624  2020-03-23  23.33
16   8625  2020-03-24  21.03
17   8626  2020-03-25  20.75
18   8627  2020-03-26  16.60
19   8628  2020-03-27  15.48
20   8629  2020-03-30  14.10
21   8630  2020-03-31  20.51
22   8631  2020-04-01  20.28
23   8632  2020-04-02  25.18
24   8633  2020-04-03  28.36
25   8634  2020-04-06  26.21
26   8635  2020-04-07  23.54
27   8636  2020-04-08  24.97
28   8637  2020-04-09  22.90
29   8638  2020-04-13  22.36
30   8639  2020-04-14  20.15
31   8640  2020-04-15  19.96
32   8641  2020-04-16  19.82
33   8642  2020-04-17  18.31
34   8643  2020-04-20 -36.98
35   8644  2020-04-21   8.91
36   8645  2020-04-22  13.64
37   8646  2020-04-23  15.06
38   8647  2020-04-24  15.99
39   8648  2020-04-27  12.17
40   8649  2020-04-28  12.40
41   8650  2020-04-29  15.04
42   8651  2020-04-30  19.23

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\2815799368.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_covid_crash_price = pd.read_sql(query, conn)

In [1]:
#4. Find the lowest price of oil in the last 10 years.

query = '''SELECT MIN(price) AS highest_price
FROM oil_prices
WHERE date BETWEEN (SELECT Min(date) FROM oil_prices) 
               AND (SELECT MAX(date) FROM oil_prices)'''
df_low_oil_price = pd.read_sql(query, conn)
print(df_low_oil_price)

NameError: name 'pd' is not defined

In [61]:
#5. Calculate the volatility of oil prices (max-min difference per year).

query = '''select year(date), max(price) - min(price) price_volatility  from oil_prices group by year(date) order by 1 desc'''
df_voilatile_price = pd.read_sql(query, conn)
print(df_voilatile_price)

   year(date)  price_volatility
0        2026              8.76
1        2025             25.29
2        2024             20.96
3        2023             27.06
4        2022             52.59
5        2021             38.17
6        2020            100.25

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\2875618415.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_voilatile_price = pd.read_sql(query, conn)

In [62]:
# STOCK_PRICES QUERIES

In [63]:
#1. Get all stock prices for a given ticker

query =  "select * from stock_prices"
df_all_stock_price = pd.read_sql(query, conn)
print(df_all_stock_price)

      index       Date     Open     High      Low    Close        Volume  \
0         0 2020-01-01      NaN      NaN      NaN      NaN           NaN
1         1 2020-01-02  3244.67  3258.14  3235.53  3257.85 3459930000.00
2         2 2020-01-03  3226.36  3246.15  3222.34  3234.85 3484700000.00
3         3 2020-01-06  3217.55  3246.84  3214.64  3246.28 3702460000.00
4         4 2020-01-07  3241.86  3244.91  3232.43  3237.18 3435910000.00
...     ...        ...      ...      ...      ...      ...           ...
4726   1572 2026-01-23 25344.60 25347.95 25025.30 25048.65     393900.00
4727   1573 2026-01-26      NaN      NaN      NaN      NaN           NaN
4728   1574 2026-01-27 25063.35 25246.65 24932.55 25175.40     618700.00
4729   1575 2026-01-28 25258.85 25372.10 25187.65 25342.75     574900.00
4730   1576 2026-01-29 25345.00 25458.15 25159.80 25418.90     582400.00

     ticker
0     ^GSPC
1     ^GSPC
2     ^GSPC
3     ^GSPC
4     ^GSPC
...     ...
4726  ^NSEI
4727  ^NSEI
4728  ^NSEI
4729  ^NSEI
4730  ^NSEI

[4731 rows x 8 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\2041430274.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_all_stock_price = pd.read_sql(query, conn)

In [64]:
#2. Find the highest closing price for NASDAQ (^IXIC)

query =  "select max(close) max_close_price from stock_prices where ticker = '^IXIC'"
df_ixix_high_close_price = pd.read_sql(query, conn)
print(df_ixix_high_close_price)

   max_close_price
0         23958.47

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\658658320.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ixix_high_close_price = pd.read_sql(query, conn)

In [65]:
#3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

query =  "SELECT date, high, low, (high - low) AS price_difference FROM stock_prices WHERE ticker = '^GSPC' ORDER BY price_difference DESC LIMIT 5"
df_gspc_high_price_diff = pd.read_sql(query, conn)
print(df_gspc_high_price_diff)

        date    high     low  price_difference
0 2025-04-09 5481.34 4948.43            532.91
1 2025-04-07 5246.57 4835.04            411.53
2 2025-04-08 5267.47 4910.42            357.05
3 2025-04-10 5353.15 5115.27            237.88
4 2025-11-20 6770.35 6534.05            236.30

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3498422185.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_gspc_high_price_diff = pd.read_sql(query, conn)

In [66]:
#4. Get monthly average closing price for each ticker

query =  "select ticker, month(date), avg(close) avg_close_price from stock_prices group by ticker, month(date) order by 1 asc, 2 desc"
df_month_avg_close_price = pd.read_sql(query, conn)
print(df_month_avg_close_price)

   ticker  month(date)  avg_close_price
0   ^GSPC           12          4976.55
1   ^GSPC           11          4849.17
2   ^GSPC           10          4766.70
3   ^GSPC            9          4707.78
4   ^GSPC            8          4715.82
5   ^GSPC            7          4653.23
6   ^GSPC            6          4465.33
7   ^GSPC            5          4404.90
8   ^GSPC            4          4325.28
9   ^GSPC            3          4267.77
10  ^GSPC            2          4459.36
11  ^GSPC            1          4741.01
12  ^IXIC           12         16157.90
13  ^IXIC           11         15633.62
14  ^IXIC           10         15390.93
15  ^IXIC            9         15140.95
16  ^IXIC            8         15124.76
17  ^IXIC            7         14992.06
18  ^IXIC            6         14200.33
19  ^IXIC            5         13730.59
20  ^IXIC            4         13423.35
21  ^IXIC            3         13284.65
22  ^IXIC            2         14048.16
23  ^IXIC            1         15073.69
24  ^NSEI           12         20013.17
25  ^NSEI           11         19641.25
26  ^NSEI           10         19584.75
27  ^NSEI            9         19393.81
28  ^NSEI            8         18943.00
29  ^NSEI            7         18727.96
30  ^NSEI            6         17964.43
31  ^NSEI            5         17815.67
32  ^NSEI            4         17578.82
33  ^NSEI            3         17014.43
34  ^NSEI            2         17896.49
35  ^NSEI            1         18899.01

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\28192928.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_month_avg_close_price = pd.read_sql(query, conn)

In [67]:
#5. Get average trading volume of NSEI in 2024

query =  "select avg(volume) avg_trading_volume from stock_prices where ticker = '^NSEI' and year(date) = '2024'"
df_avg_trade_vol_2024 = pd.read_sql(query, conn)
print(df_avg_trade_vol_2024)

   avg_trading_volume
0           313560.16

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3006689221.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_avg_trade_vol_2024 = pd.read_sql(query, conn)

In [68]:
# Join Queries (Cross-Market Analysis)

In [69]:
#1. Compare Bitcoin vs Oil average price in 2025.

query =  '''select '2025' year
		, (select avg(price_inr) from crypto_prices where coin_id = 'bitcoin' and year(timestamp) = '2025') bitocoin_avg_price
		, (select avg(price) from oil_prices where year(date) = '2025') oil_avg_price '''
df_avg_price = pd.read_sql(query, conn)
print(df_avg_price)

   year  bitocoin_avg_price  oil_avg_price
0  2025          9272501.38          65.39

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\1803851750.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_avg_price = pd.read_sql(query, conn)

In [81]:
#2. Check if Bitcoin moves with S&P 500 (correlation idea).

query =  '''select s.ticker, cast(s.date as date) date, s.open sp500_price, c.coin_id, c.price_inr bitcoint_price
from stock_prices s inner join crypto_prices c on s.date = c.timestamp
where ticker = '^GSPC' and coin_id = 'bitcoin'
order by s.date desc'''
df_bitcoin_sp500 = pd.read_sql(query, conn)
print(df_bitcoin_sp500)

    ticker        date  sp500_price  coin_id  bitcoint_price
0    ^GSPC  2026-01-29      6977.74  bitcoin      8206661.92
1    ^GSPC  2026-01-28      7002.00  bitcoin      8165356.49
2    ^GSPC  2026-01-27      6965.96  bitcoin      8098992.12
3    ^GSPC  2026-01-26      6923.23  bitcoin      7931480.81
4    ^GSPC  2026-01-23      6907.85  bitcoin      8189307.78
..     ...         ...          ...      ...             ...
197  ^GSPC  2025-04-28      5529.22  bitcoin      8009924.38
198  ^GSPC  2025-04-25      5489.73  bitcoin      8000169.78
199  ^GSPC  2025-04-24      5381.38  bitcoin      8003280.21
200  ^GSPC  2025-04-23      5395.92  bitcoin      7975735.89
201  ^GSPC  2025-04-22      5207.67  bitcoin      7447341.99

[202 rows x 5 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\284213353.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_bitcoin_sp500 = pd.read_sql(query, conn)

In [82]:
#3. Compare Ethereum and NASDAQ daily prices for 2025.

query =  '''SELECT 
    c.coin_id, 
    c.timestamp, 
    c.price_inr ethereum_price, 
    s.ticker, 
    s.close nasdaq_price
FROM crypto_prices c
INNER JOIN stock_prices s 
    ON DATE(c.timestamp) = s.date
WHERE c.coin_id = 'Ethereum' 
  AND s.ticker = '^IXIC'
  AND YEAR(s.date) = 2025
ORDER BY s.date'''
df_daily_price = pd.read_sql(query, conn)
print(df_daily_price)

      coin_id   timestamp  ethereum_price ticker  nasdaq_price
0    ethereum  2025-04-22       134334.01  ^IXIC      16300.42
1    ethereum  2025-04-23       149984.44  ^IXIC      16708.05
2    ethereum  2025-04-24       153384.69  ^IXIC      17166.04
3    ethereum  2025-04-25       150793.82  ^IXIC      17382.94
4    ethereum  2025-04-28       153154.65  ^IXIC      17366.13
..        ...         ...             ...    ...           ...
176  ethereum  2025-12-24       265308.33  ^IXIC      23613.31
177  ethereum  2025-12-26       261698.84  ^IXIC      23593.10
178  ethereum  2025-12-29       264760.55  ^IXIC      23474.35
179  ethereum  2025-12-30       263786.42  ^IXIC      23419.08
180  ethereum  2025-12-31       266620.87  ^IXIC      23241.99

[181 rows x 5 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3044193352.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_daily_price = pd.read_sql(query, conn)

In [84]:
#4. Find days when oil price spiked and compare with Bitcoin price change

query =  '''select c.coin_id, c.timestamp, c.price_inr bitcoin_price, o.price oil_price
from crypto_prices c inner join oil_prices o on (c.timestamp = o.date and o.price > c.price_inr)
where coin_id = 'bitcoin' order by c.timestamp desc'''
df_oil_bitocoin = pd.read_sql(query, conn)
print(df_oil_bitocoin)

Empty DataFrame
Columns: [coin_id, timestamp, bitcoin_price, oil_price]
Index: []

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\2880722469.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_oil_bitocoin = pd.read_sql(query, conn)

In [86]:
#5.Compare top 3 coins daily price trend vs Nifty (^NSEI).

query =  '''select s.ticker, cast(s.date as date) date, s.open, c.coin_id, c.price_inr
from stock_prices s inner join crypto_prices c on s.date = c.timestamp
where ticker = '^NSEI'
order by s.date desc'''
df_topcoins_nifty = pd.read_sql(query, conn)
print(df_topcoins_nifty)

    ticker        date     open   coin_id  price_inr
0    ^NSEI  2026-01-29 25345.00   bitcoin 8206661.92
1    ^NSEI  2026-01-29 25345.00  ethereum  276752.68
2    ^NSEI  2026-01-28 25258.85   bitcoin 8165356.49
3    ^NSEI  2026-01-28 25258.85  ethereum  276537.24
4    ^NSEI  2026-01-27 25063.35   bitcoin 8098992.12
..     ...         ...      ...       ...        ...
399  ^NSEI  2025-04-24 24277.90  ethereum  153384.69
400  ^NSEI  2025-04-23 24357.60   bitcoin 7975735.89
401  ^NSEI  2025-04-23 24357.60  ethereum  149984.44
402  ^NSEI  2025-04-22 24185.40   bitcoin 7447341.99
403  ^NSEI  2025-04-22 24185.40  ethereum  134334.01

[404 rows x 5 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\1285173703.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_topcoins_nifty = pd.read_sql(query, conn)

In [87]:
#6.Compare stock prices (^GSPC) with crude oil prices on the same dates

query =  '''select s.ticker, cast(s.date as date) date, s.open ticker_price,  o.price oil_price
from stock_prices s inner join oil_prices o on s.date = o.date
where ticker = '^GSPC'
order by s.date desc'''
df_crudeoil_gspc = pd.read_sql(query, conn)
print(df_crudeoil_gspc)

     ticker        date  ticker_price  oil_price
0     ^GSPC  2026-01-29       6977.74      64.77
1     ^GSPC  2026-01-28       7002.00      62.75
2     ^GSPC  2026-01-27       6965.96      62.04
3     ^GSPC  2026-01-26       6923.23      60.46
4     ^GSPC  2026-01-23       6907.85      60.70
...     ...         ...           ...        ...
1514  ^GSPC  2020-01-08       3238.59      59.65
1515  ^GSPC  2020-01-07       3241.86      62.70
1516  ^GSPC  2020-01-06       3217.55      63.27
1517  ^GSPC  2020-01-03       3226.36      63.00
1518  ^GSPC  2020-01-02       3244.67      61.17

[1519 rows x 4 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3498830847.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_crudeoil_gspc = pd.read_sql(query, conn)

In [88]:
#7.Correlate Bitcoin closing price with crude oil closing price (same date)

query =  '''select c.coin_id, c.timestamp, c.price_inr bitcoin_price, o.price oil_price
from crypto_prices c inner join oil_prices o on c.timestamp = o.date
where coin_id = 'bitcoin' order by c.timestamp desc'''
df_bitcoin_oil_close = pd.read_sql(query, conn)
print(df_bitcoin_oil_close)

     coin_id   timestamp  bitcoin_price  oil_price
0    bitcoin  2026-01-30     7762053.97      64.50
1    bitcoin  2026-01-29     8206661.92      64.77
2    bitcoin  2026-01-28     8165356.49      62.75
3    bitcoin  2026-01-27     8098992.12      62.04
4    bitcoin  2026-01-26     7931480.81      60.46
..       ...         ...            ...        ...
189  bitcoin  2025-04-28     8009924.38      63.30
190  bitcoin  2025-04-25     8000169.78      63.85
191  bitcoin  2025-04-24     8003280.21      63.55
192  bitcoin  2025-04-23     7975735.89      62.64
193  bitcoin  2025-04-22     7447341.99      64.60

[194 rows x 4 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\60886352.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_bitcoin_oil_close = pd.read_sql(query, conn)

In [89]:
#8.Compare NASDAQ (^IXIC) with Ethereum price trends

query =  '''SELECT c.coin_id, c.timestamp date, c.price_inr ethereum_price, s.ticker, s.close nasdaq_price
FROM crypto_prices c INNER JOIN stock_prices s ON DATE(c.timestamp) = s.date
WHERE c.coin_id = 'Ethereum' AND s.ticker = '^IXIC'
ORDER BY s.date desc'''
df_ixic_eretherum_price = pd.read_sql(query, conn)
print(df_ixic_eretherum_price)

      coin_id        date  ethereum_price ticker  nasdaq_price
0    ethereum  2026-01-29       276752.68  ^IXIC      23685.12
1    ethereum  2026-01-28       276537.24  ^IXIC      23857.45
2    ethereum  2026-01-27       268521.11  ^IXIC      23817.10
3    ethereum  2026-01-26       257898.21  ^IXIC      23601.36
4    ethereum  2026-01-23       269940.05  ^IXIC      23501.24
..        ...         ...             ...    ...           ...
197  ethereum  2025-04-28       153154.65  ^IXIC      17366.13
198  ethereum  2025-04-25       150793.82  ^IXIC      17382.94
199  ethereum  2025-04-24       153384.69  ^IXIC      17166.04
200  ethereum  2025-04-23       149984.44  ^IXIC      16708.05
201  ethereum  2025-04-22       134334.01  ^IXIC      16300.42

[202 rows x 5 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\1931759517.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ixic_eretherum_price = pd.read_sql(query, conn)

In [90]:
#9.Join top 3 crypto coins with stock indices for 2025

query =  '''SELECT c.coin_id, c.timestamp date, c.price_inr crypto_price, s.ticker, s.close stock_price
FROM crypto_prices c INNER JOIN stock_prices s ON DATE(c.timestamp) = s.date
ORDER BY s.date desc'''
df_coins_stock_price = pd.read_sql(query, conn)
print(df_coins_stock_price)

       coin_id        date  crypto_price ticker  stock_price
0     ethereum  2026-01-29     276752.68  ^GSPC      6969.01
1      bitcoin  2026-01-29    8206661.92  ^GSPC      6969.01
2     ethereum  2026-01-29     276752.68  ^IXIC     23685.12
3      bitcoin  2026-01-29    8206661.92  ^IXIC     23685.12
4     ethereum  2026-01-29     276752.68  ^NSEI     25418.90
...        ...         ...           ...    ...          ...
1207   bitcoin  2025-04-22    7447341.99  ^GSPC      5287.76
1208  ethereum  2025-04-22     134334.01  ^IXIC     16300.42
1209   bitcoin  2025-04-22    7447341.99  ^IXIC     16300.42
1210  ethereum  2025-04-22     134334.01  ^NSEI     24167.25
1211   bitcoin  2025-04-22    7447341.99  ^NSEI     24167.25

[1212 rows x 5 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\1313555779.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_coins_stock_price = pd.read_sql(query, conn)

In [91]:
#10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

query =  '''select c.coin_id, c.timestamp, c.price_inr bitcoin_price, o.price oil_price, s.ticker, s.close stock_price
from crypto_prices c inner join oil_prices o on c.timestamp = o.date
	inner join stock_prices s on o.date = s.date
where coin_id = 'bitcoin' order by c.timestamp desc'''
df_bitcoin_stock_oil_price = pd.read_sql(query, conn)
print(df_bitcoin_stock_oil_price)

     coin_id   timestamp  bitcoin_price  oil_price ticker  stock_price
0    bitcoin  2026-01-29     8206661.92      64.77  ^GSPC      6969.01
1    bitcoin  2026-01-29     8206661.92      64.77  ^IXIC     23685.12
2    bitcoin  2026-01-29     8206661.92      64.77  ^NSEI     25418.90
3    bitcoin  2026-01-28     8165356.49      62.75  ^GSPC      6978.03
4    bitcoin  2026-01-28     8165356.49      62.75  ^IXIC     23857.45
..       ...         ...            ...        ...    ...          ...
574  bitcoin  2025-04-23     7975735.89      62.64  ^IXIC     16708.05
575  bitcoin  2025-04-23     7975735.89      62.64  ^NSEI     24328.95
576  bitcoin  2025-04-22     7447341.99      64.60  ^GSPC      5287.76
577  bitcoin  2025-04-22     7447341.99      64.60  ^IXIC     16300.42
578  bitcoin  2025-04-22     7447341.99      64.60  ^NSEI     24167.25

[579 rows x 6 columns]

C:\Users\HP\AppData\Local\Temp\ipykernel_10828\3622317861.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_bitcoin_stock_oil_price = pd.read_sql(query, conn)